# Generated by Django 5.2.8 on 2026-04-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Catégorie d'arrêt",
                'verbose_name_plural': "Catégories d'arrêts",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('intitule', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arret', models.DateField()),
                ('section', models.CharField(default='Non défini', max_length=200)),
                ('domaine', models.CharField(default='Non défini', max_length=200)),
                ('mots_cles', models.CharField(default='Non défini', max_length=255)),
                ('parties', models.TextField(default='Non défini')),
                ('decision_attaquee', models.TextField(default='Non défini')),
                ('textes_loi', models.TextField(default='Non défini')),
                ('resume', models.TextField(default='Non défini')),
                ('le_texte', models.TextField(default='Non défini')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('reference', models.CharField(default='Non défini', max_length=255, unique=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='arret.categorie')),
            ],
            options={
                'verbose_name': 'Arrêt',
                'verbose_name_plural': 'Arrêts',
                'ordering': ['-date_arret', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True)),
                ('contenu', models.TextField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='arret.chapitre')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('sujet', models.CharField(choices=[('info', 'Information'), ('requete', 'Requête juridique'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('encours', 'En cours'), ('traite', 'Traité')], default='nouveau', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TexteJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_texte', models.CharField(choices=[('constitution', 'Constitution'), ('loi', 'Loi'), ('arret', 'Arrêt')], max_length=20)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('cr', 'Créole')], default='fr', max_length=2)),
                ('date_publication', models.DateField()),
                ('est_version_amendee', models.BooleanField(default=False)),
                ('version_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='arret.textejuridique')),
            ],
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('intitule', models.CharField(max_length=255)),
                ('texte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='arret.textejuridique')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='arret.titre'),
        ),
    ]
