# Generated by Django 5.2.8 on 2026-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(upload_to='revues/')),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Revue',
                'verbose_name_plural': 'Revues',
                'ordering': ['-annee', '-date_publication'],
            },
        ),
    ]
