# Generated by Django 5.2.8 on 2026-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arret', '0002_revue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revue',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='revues/'),
        ),
    ]
